Checkpoints every 100B steps
maxitg/PostTagSystem pull request #30
Opened 2021-03-15 20:51 UTC by maxitg

## Changes

* Adds `checkpointFlags.multipleOfHundredBillionEventCounts` which inserts checkpoints every 100B events.
* This is enabled by default in `PostTagSearcher`.
* This should insert a checkpoint every 5-10 minutes.

## Comments

* I assume memory use is not a concern in the pounce mode. Otherwise, we can increase 100B to 1T.

## Examples

* The following should now terminate sooner (I did not actually try running it):
```console
$ ./wolfram-postproject --chase --initstart 1073741823 --initcount 1 --initsize 30
```

* There is a disabled test as well:
```c++
PostTagHistory evaluator;
const TagState init(24, 9603135, 0);
const auto result = PostTagHistory().evaluate(
    PostTagHistory::NamedRule::Post, init, PostTagHistory::EvaluationLimits(), {{}, {false, true}});
constexpr uint64_t hundredBillion = 100000000000;
ASSERT_GT(result.eventCount, hundredBillion);
ASSERT_LT(result.eventCount, 2 * hundredBillion);
```

2021-03-15 22:23 UTC, okofish requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/posttagsystem/30)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @maxitg and @okofish)

___
*[libPostTagSystem/PostTagHistory.hpp, line 36 at r1](https://reviewable.io/reviews/maxitg/posttagsystem/30#-MVrwPVREhxNTuuJzzn1:-MVrwPVREhxNTuuJzzn2:b-g1yqdc) ([raw file](https://github.com/maxitg/posttagsystem/blob/3bf0878eabc6dce1a40c0239e8676b89c3f1a1d5/libPostTagSystem/PostTagHistory.hpp#L36)):*
> ```cpp
>   struct CheckpointSpecFlags {
>     bool powerOfTwoEventCounts;
>     bool multipleOfHundredBillionEventCounts;
> ```

Thanks for implementing this quickly!

I think this should be an adjustable parameter like `uint64_t multipleOfNEventCounts` rather than a Boolean flag with a fixed interval. Then I could expose a CLI option to change it. `multipleOfNEventCounts = 0` would disable this (probably the default).
___
*[libPostTagSystem/test/PostTagSystem_test.cpp, line 109 at r1](https://reviewable.io/reviews/maxitg/posttagsystem/30#-MVryXK64lPlWiub5bP5:-MVryXK64lPlWiub5bP6:bv2vpw0) ([raw file](https://github.com/maxitg/posttagsystem/blob/3bf0878eabc6dce1a40c0239e8676b89c3f1a1d5/libPostTagSystem/test/PostTagSystem_test.cpp#L109)):*
> ```cpp
> }
> 
> // This test takes unreasonably long time, and is unlikely to break
> ```

With the flag as an adjustable integer you could choose a smaller value for this test.


<!-- Sent from Reviewable.io -->

2021-03-15 22:28 UTC, okofish requested changes
> *[Reviewable](https://reviewable.io/reviews/maxitg/posttagsystem/30)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @maxitg and @okofish)

___
*[libPostTagSystem/PostTagHistory.hpp, line 36 at r1](https://reviewable.io/reviews/maxitg/posttagsystem/30#-MVrwPVREhxNTuuJzzn1:-MVs-H904oAwPkLlWA7R:bq8ecul) ([raw file](https://github.com/maxitg/posttagsystem/blob/3bf0878eabc6dce1a40c0239e8676b89c3f1a1d5/libPostTagSystem/PostTagHistory.hpp#L36)):*
<details><summary><i>Previously, okofish (Jesse Friedman) wrote…</i></summary><blockquote>

Thanks for implementing this quickly!

I think this should be an adjustable parameter like `uint64_t multipleOfNEventCounts` rather than a Boolean flag with a fixed interval. Then I could expose a CLI option to change it. `multipleOfNEventCounts = 0` would disable this (probably the default).
</blockquote></details>

Or the default could be 100B as you have it now.


<!-- Sent from Reviewable.io -->

2021-03-15 23:59 UTC, maxitg reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/posttagsystem/30)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @okofish)

___
*[libPostTagSystem/PostTagHistory.hpp, line 36 at r1](https://reviewable.io/reviews/maxitg/posttagsystem/30#-MVrwPVREhxNTuuJzzn1:-MVsJuRvEHWyxXjHq-xT:b-bn45di) ([raw file](https://github.com/maxitg/posttagsystem/blob/3bf0878eabc6dce1a40c0239e8676b89c3f1a1d5/libPostTagSystem/PostTagHistory.hpp#L36)):*
<details><summary><i>Previously, okofish (Jesse Friedman) wrote…</i></summary><blockquote>

Or the default could be 100B as you have it now.
</blockquote></details>

Done. Disabled by default for consistency.
___
*[libPostTagSystem/test/PostTagSystem_test.cpp, line 109 at r1](https://reviewable.io/reviews/maxitg/posttagsystem/30#-MVryXK64lPlWiub5bP5:-MVsK05nBR3QfjBwtGKp:b-896fix) ([raw file](https://github.com/maxitg/posttagsystem/blob/3bf0878eabc6dce1a40c0239e8676b89c3f1a1d5/libPostTagSystem/test/PostTagSystem_test.cpp#L109)):*
<details><summary><i>Previously, okofish (Jesse Friedman) wrote…</i></summary><blockquote>

With the flag as an adjustable integer you could choose a smaller value for this test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-16 00:14 UTC, okofish requested changes
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/posttagsystem/30)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @maxitg and @okofish)

___
*[libPostTagSystem/test/PostTagSystem_test.cpp, line 109 at r1](https://reviewable.io/reviews/maxitg/posttagsystem/30#-MVryXK64lPlWiub5bP5:-MVsNCTX8Fk_q6afd2S6:b91up8z) ([raw file](https://github.com/maxitg/posttagsystem/blob/3bf0878eabc6dce1a40c0239e8676b89c3f1a1d5/libPostTagSystem/test/PostTagSystem_test.cpp#L109)):*
<details><summary><i>Previously, maxitg (Max Piskunov) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks good. You can probably remove the comment now that the test is enabled.


<!-- Sent from Reviewable.io -->

2021-03-16 00:16 UTC, maxitg reviewed
> *[Reviewable](https://reviewable.io/reviews/maxitg/posttagsystem/30)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @okofish)

___
*[libPostTagSystem/test/PostTagSystem_test.cpp, line 109 at r1](https://reviewable.io/reviews/maxitg/posttagsystem/30#-MVryXK64lPlWiub5bP5:-MVsNxNY2FDBE7CxANuq:b-896fix) ([raw file](https://github.com/maxitg/posttagsystem/blob/3bf0878eabc6dce1a40c0239e8676b89c3f1a1d5/libPostTagSystem/test/PostTagSystem_test.cpp#L109)):*
<details><summary><i>Previously, okofish (Jesse Friedman) wrote…</i></summary><blockquote>

Looks good. You can probably remove the comment now that the test is enabled.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-16 00:16 UTC, okofish reviewed
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/maxitg/posttagsystem/30)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @okofish)



<!-- Sent from Reviewable.io -->

2021-03-16 00:16 UTC, okofish approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/maxitg/posttagsystem/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @maxitg)



<!-- Sent from Reviewable.io -->

2021-03-16 00:24 UTC, merged